services:
  postgres:
    image: postgres:latest
    restart: "no"
    ports:
      - "1337:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: lab7